apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumez-prometheus-exporter-deployment
  labels:
    app: volumez-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volumez-prometheus-exporter
  template:
    metadata:
      labels:
        app: volumez-prometheus-exporter
    spec:
      containers:
      - name: volumez-prometheus-exporter
        image: sween/volumez-prometheus-exporter:latest
        ports:
        - containerPort: 5000
        env:
        - name: VLZ_USER
          valueFrom:
            secretKeyRef:
              name: volumez-secret
              key: volumez_user
        - name: VLZ_PASS
          valueFrom:
            secretKeyRef:
              name: vlz-secret
              key: vlz_pass
        - name: VLZ_USERPOOLID
          valueFrom:
            secretKeyRef:
              name: vlz-secret
              key: vlz_userpoolid
        - name: VLZ_CLIENTID
          valueFrom:
            secretKeyRef:
              name: vlz-secret
              key: vlz_clientid
        - name: VLZ_POLLING
          valueFrom:
            secretKeyRef:
              name: vlz-secret
              key: vlz_polling